name: Build Data Generator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  Scan:
    uses: Astridstar/github_workflows/.github/workflows/codeql.yml@latest

  Build:
    environment: UAT
    runs-on: ubuntu-latest
    needs: Scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup dotnet environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.*

      - name: Install dependencies
        run: dotnet restore

      - name: Build the code
        run: dotnet Build
        
      
